data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  mappings_dir: "data/processed/mappings"
  user_mapping_file: "user_mapping.pkl"
  item_mapping_file: "item_mapping.pkl"
  interactions_file: "data/processed/interactions/user_item_interactions.csv"
  features_file: "data/processed/features/item_properties_clean.csv"
